// ACTION IDs
export const SET_THEME = 'SET_THEME';


export const GET_DICTIONARY_SEARCH = 'GET_DICTIONARY_SEARCH';
export const SET_DICTIONARY_SEARCH = 'SET_DICTIONARY_SEARCH';
export const GET_DICTIONARY_SEARCHES = 'GET_DICTIONARY_SEARCHES';
export const SET_DICTIONARY_SEARCHES = 'SET_DICTIONARY_SEARCHES';