export const SET_INDEX = 'SET_INDEX';
export const SET_INDICES = 'SET_INDICES';

export const SET_CLUSTER = 'SET_CLUSTER';
export const SET_CLUSTER_LIST = 'SET_CLUSTER_LIST';

export const SET_ACTIVE_SETTING_INDEX = 'SET_ACTIVE_SETTING_INDEX';
export const SET_SETTING_DICTIONARIES = 'SET_SETTING_DICTIONARIES';
export const SET_DICTIONARY_DATASET = 'SET_DICTIONARY_DATASET';

export const SET_INDICES_MAPPING = 'SET_INDICES_MAPPING';
export const SET_SERVER_SUMMARY = 'SET_SERVER_SUMMARY';
export const SET_API_MANAGEMENT = 'SET_API_MANAGEMENT';
export const SET_CLUSTER_INFO = 'SET_CLUSTER_INFO';
export const SET_NODES_INFO = 'SET_NODES_INFO';
export const SET_INDICES_INFO = 'SET_INDICES_INFO';
export const SET_HEALTH_INFO = 'SET_HEALTH_INFO';
export const SET_SHARDS_INFO = 'SET_SHARDS_INFO';
export const SET_INDICES_DATA = 'SET_INDICES_DATA';
export const SET_INDEX_MAPPING = 'SET_INDEX_MAPPING';
export const SET_INDEX_RESULT = 'SET_INDEX_RESULT';
export const SET_RUNNING_INDEX = 'SET_RUNNING_INDEX';
export const SET_INDEX_STATUS = 'SET_INDEX_STATUS';
export const SET_INDEX_ALIAS = 'SET_INDEX_ALIAS';

export const SET_REFERENCE_SEARCH_KEYWORD = 'SET_REFERENCE_SEARCH_KEYWORD';
export const SET_REFERENCE_TEMPLATE_LIST = 'SET_REFERENCE_TEMPLATE_LIST';
export const SET_REFERENCE_TEMPLATE = 'SET_REFERENCE_TEMPLATE';
export const SET_REFERENCE_RESULT_ALL = 'SET_REFERENCE_RESULT_ALL';
export const SET_REFERENCE_RESULT = 'SET_REFERENCE_RESULT';

export const SET_INDEX_TEMPLATES = 'SET_INDEX_TEMPLATES';
export const SET_INDEX_TEMPLATE = 'SET_INDEX_TEMPLATE';

export const SET_FASTCATX_SERVER = 'SET_FASTCATX_SERVER';
export const SET_FASTCATX_AUTH_USER = 'SET_FASTCATX_AUTH_USER';

export const SET_ROLE_LIST = 'SET_ROLE_LIST';
export const SET_ROLE = 'SET_ROLE';

export const SET_USER_LIST = 'SET_USER_LIST';
export const SET_USER = 'SET_USER';

export const SET_CLUSTER_SETTINGS = 'SET_CLUSTER_SETTINGS';

export const SET_INDEX_INFO_LIST = 'SET_INDEX_INFO_LIST';
export const SET_INDEX_ALIASES = 'SET_INDEX_ALIASES';
export const SET_INDEX_SETTINGS = 'SET_INDEX_SETTINGS';
export const SET_INDEX_MAPPINGS = 'SET_INDEX_MAPPINGS';