export const SET_INDEX = 'SET_INDEX';
export const SET_INDICES = 'SET_INDICES';

export const SET_CLUSTER = 'SET_CLUSTER';
export const SET_CLUSTER_LIST = 'SET_CLUSTER_LIST';

export const SET_ACTIVE_SETTING_INDEX = 'SET_ACTIVE_SETTING_INDEX';
export const SET_SETTING_DICTIONARIES = 'SET_SETTING_DICTIONARIES';
export const SET_DICTIONARY_DATASET = 'SET_DICTIONARY_DATASET';

export const SET_DICTIONARY_SEARCH_LIST = 'SET_DICTIONARY_SEARCH_LIST';
export const SET_DICTIONARY = 'SET_DICTIONARY';
export const SET_SUMMARY = 'SET_SUMMARY';

export const SET_INDICES_MAPPING = 'SET_INDICES_MAPPING';
export const SET_SERVER_SUMMARY = 'SET_SERVER_SUMMARY';
export const SET_API_MANAGEMENT = 'SET_API_MANAGEMENT';
export const SET_CLUSTER_INFO = 'SET_CLUSTER_INFO';
export const SET_NODES_INFO = 'SET_NODES_INFO';
export const SET_INDICES_INFO = 'SET_INDICES_INFO';
export const SET_HEALTH_INFO = 'SET_HEALTH_INFO';
export const SET_SHARDS_INFO = 'SET_SHARDS_INFO';
export const SET_MOVE_INFO = 'SET_MOVE_INFO';
export const SET_ROUTE_INFO = 'SET_ROUTE_INFO';
export const SET_REMOVE_INFO = 'SET_REMOVE_INFO';

export const SET_INDEX_MAPPING = 'SET_INDEX_MAPPING';
export const SET_INDEX_RESULT = 'SET_INDEX_RESULT';
export const SET_RUNNING_INDEX = 'SET_RUNNING_INDEX';
export const SET_INDEX_STATUS = 'SET_INDEX_STATUS';
export const SET_INDEX_ALIAS = 'SET_INDEX_ALIAS';

export const SET_REFERENCE_SEARCH_KEYWORD = 'SET_REFERENCE_SEARCH_KEYWORD';
export const SET_REFERENCE_TEMPLATE_LIST = 'SET_REFERENCE_TEMPLATE_LIST';
export const SET_REFERENCE_TEMPLATE = 'SET_REFERENCE_TEMPLATE';
export const SET_REFERENCE_RESULT_ALL = 'SET_REFERENCE_RESULT_ALL';
export const SET_REFERENCE_RESULT = 'SET_REFERENCE_RESULT';

export const SET_INDEX_TEMPLATES = 'SET_INDEX_TEMPLATES';
export const SET_INDEX_TEMPLATE = 'SET_INDEX_TEMPLATE';

export const SET_DSEARCH_SERVER = 'SET_DSEARCH_SERVER';
export const SET_DSEARCH_AUTH_USER = 'SET_DSEARCH_AUTH_USER';

export const SET_ROLE_LIST = 'SET_ROLE_LIST';
export const SET_ROLE = 'SET_ROLE';

export const SET_USER_LIST = 'SET_USER_LIST';
export const SET_USER = 'SET_USER';

export const SET_CLUSTER_SETTINGS = 'SET_CLUSTER_SETTINGS';
export const SET_DSEARCH_SETTINGS = 'SET_DSEARCH_SETTINGS';

export const SET_INDEX_INFO_LIST = 'SET_INDEX_INFO_LIST';
export const SET_INDEX_ALIASES = 'SET_INDEX_ALIASES';
export const SET_INDEX_SETTINGS = 'SET_INDEX_SETTINGS';
export const SET_INDEX_MAPPINGS = 'SET_INDEX_MAPPINGS';
export const SET_INDEX_STATE = 'SET_INDEX_STATE';
export const SET_INDEX_DOCUMENTS = 'SET_INDEX_DOCUMENTS';

export const SET_COLLECTION_INDEX_SUFFIX = 'SET_COLLECTION_INDEX_SUFFIX';
export const SET_COLLECTION = 'SET_COLLECTION';
export const SET_COLLECTION_LIST = 'SET_COLLECTION_LIST';

export const SET_TOOLS_ANALYZER_LIST = 'SET_TOOLS_ANALYZER_LIST';
export const SET_TOOLS_PLUGIN_LIST = 'SET_TOOLS_PLUGIN_LIST';
export const SET_TOOLS_ANALYZE_BRIEF_RESULT = 'SET_TOOLS_ANALYZE_BRIEF_RESULT';
export const SET_TOOLS_ANALYZE_DETAIL_RESULT = 'SET_TOOLS_ANALYZE_DETAIL_RESULT';
export const RESET_TOOLS_RESULTS = 'RESET_TOOLS_RESULTS';

export const SET_RANKING_TUNING_DOCUMENT = 'SET_RANKING_TUNING_DOCUMENT';


export const SET_JDBC_INDEX = 'SET_JDBC_INDEX';
export const SET_JDBC_LIST = 'SET_JDBC_LIST';
export const SET_JDBC_ACCESS_TEST = 'SET_JDBC_ACCESS_TEST';
export const SET_JDBC_ADD_RESULT = 'SET_JDBC_ADD_RESULT';
export const SET_JDBC_DELETE_RESULT = 'SET_JDBC_DELETE_RESULT';
export const SET_JDBC_UPDATE_RESULT = 'SET_JDBC_UPDATE_RESULT';

export const SET_PIPELINE = "SET_PIPELINE";
export const SET_PIPELINE_RESULT = "SET_PIPELINE_RESULT";
export const SET_PIPELINE_LIST = 'SET_PIPELINE_LIST';
export const ADD_PIPELINE = 'ADD_PIPELINE';
export const DELETE_PIPELINE = 'DELETE_PIPELINE';

export const SET_COLLECTION_JOB = 'SET_COLLECTION_JOB';

export const SET_COLLECTION_INDEX_HISTORY_LIST = 'SET_COLLECTION_INDEX_HISTORY_LIST';
export const SET_CAT_INDEX_TEMPLATE_LIST = 'SET_CAT_INDEX_TEMPLATE_LIST';
export const SET_INDEX_DOCUMENT_SOURCE_RESPONSE = 'SET_INDEX_DOCUMENT_SOURCE_RESPONSE';
export const SET_DASHBOARD_INDICES_INFO='SET_DASHBOARD_INDICES_INFO';

export const SET_PLUGIN_KEYWORD='SET_PLUGIN_KEYWORD'
export const SET_AUTOCOMPLETE_URL ='SET_AUTOCOMPLETE_URL'

export const SET_SERVER_CHECK ='SET_SERVER_CHECK'

export const SET_COMMENTS = 'SET_COMMENTS';

// 문서 분석 탭, CR만 담당
export const READ_SEARCH_QUERYS = 'READ_SEARCH_QUERYS';
export const CREATE_SEARCH_QUERY = 'CREATE_SEARCH_QUERY';
export const DELETE_SEARCH_QUERY = 'DELETE_SEARCH_QUERY';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';

export const ANALYSIS_DOCUMENT = 'ANALYSIS_DOCUMENT';
export const ANALYSIS_DOCUMENT_DETAIL = 'ANALYSIS_DOCUMENT_DETAIL';